import './globals.css'
import './index.scss';
import Script from "next/script";
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ticket',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* 아임포트 결제를 위한 script */}
        <Script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.min.js" ></Script>
        <Script type="text/javascript" src="https://cdn.iamport.kr/js/iamport.payment-1.1.8.js"></Script>
      </head>
      <body className={inter.className}>{children}
        <div id='modal' />
      </body>
    </html>
  )
}
