import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";
import "./index.scss";
// import { Inter } from 'next/font/google'
import QueryProviders from "@/util/queryProvider";
import RecoilRootProvider from "@/util/recoilRootProvider";
import CookiesRootProvider from "@/util/cookieProvider";
import ApolloProviders from "@/util/apolloProvider";
import Location from "@/components/location/Location";
import LoginCheck from "@/components/loginCheck/LoginCheck";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Sse from "@/components/sse/Sse";
// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "ticket",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* 아임포트 결제를 위한 script */}
        <Script
          type="text/javascript"
          src="https://code.jquery.com/jquery-1.12.4.min.js"
        />
        <Script
          type="text/javascript"
          src="https://cdn.iamport.kr/js/iamport.payment-1.1.8.js"
        />
        {/* 카카오 로그인을 위한 script */}
        <Script
          src="https://t1.kakaocdn.net/kakao_js_sdk/2.4.0/kakao.min.js"
          integrity="sha384-mXVrIX2T/Kszp6Z0aEWaA8Nm7J6/ZeWXbL8UpGRjKwWe56Srd/iyNmWMBhcItAjH"
          crossOrigin="anonymous"
        />
        <Script src="https://developers.kakao.com/sdk/js/kakao.js" />
        {/* 네이버 지도 */}
        <Script
          type="text/javascript"
          src="http://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=ugm16gkcw2"
        />
        <Script
          type="text/javascript"
          src="https://oapi.map.naver.com/openapi/v3/maps.js?ncpClientId=ugm16gkcw2&submodules=geocoder"
        ></Script>
      </head>
      <body>
        <QueryProviders>
          <CookiesRootProvider>
            <RecoilRootProvider>
              <ApolloProviders>
                {children}
                <LoginCheck />
                <Location />
                <Sse />
                <ToastContainer
                  position="top-center"
                  autoClose={5000}
                  hideProgressBar={false}
                  newestOnTop={false}
                  closeOnClick
                  rtl={false}
                  pauseOnFocusLoss
                  draggable
                  pauseOnHover
                  theme="light"
                />
              </ApolloProviders>
            </RecoilRootProvider>
          </CookiesRootProvider>
        </QueryProviders>
        <div id="modal" />
      </body>
    </html>
  );
}
